[2022-11-30T09:09:40.374+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: pratice_pg.pg_prepare manual__2022-11-30T09:09:37.763109+00:00 [queued]>
[2022-11-30T09:09:40.380+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: pratice_pg.pg_prepare manual__2022-11-30T09:09:37.763109+00:00 [queued]>
[2022-11-30T09:09:40.380+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T09:09:40.380+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-30T09:09:40.380+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T09:09:40.388+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): pg_prepare> on 2022-11-30 09:09:37.763109+00:00
[2022-11-30T09:09:40.392+0000] {standard_task_runner.py:55} INFO - Started process 2743 to run task
[2022-11-30T09:09:40.394+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pratice_pg', 'pg_prepare', 'manual__2022-11-30T09:09:37.763109+00:00', '--job-id', '700', '--raw', '--subdir', 'DAGS_FOLDER/practice_pg.py', '--cfg-path', '/tmp/tmpb95opxo9']
[2022-11-30T09:09:40.395+0000] {standard_task_runner.py:83} INFO - Job 700: Subtask pg_prepare
[2022-11-30T09:09:40.438+0000] {task_command.py:376} INFO - Running <TaskInstance: pratice_pg.pg_prepare manual__2022-11-30T09:09:37.763109+00:00 [running]> on host 0fcad1446026
[2022-11-30T09:09:40.480+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pratice_pg
AIRFLOW_CTX_TASK_ID=pg_prepare
AIRFLOW_CTX_EXECUTION_DATE=2022-11-30T09:09:37.763109+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-30T09:09:37.763109+00:00
[2022-11-30T09:09:40.486+0000] {base.py:71} INFO - Using connection ID 'pgdb' for task execution.
[2022-11-30T09:09:40.604+0000] {base.py:71} INFO - Using connection ID 'pgdb' for task execution.
[2022-11-30T09:09:40.678+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/practice_pg.py", line 29, in pg_prepare
    cursor.execute(copy_query)
psycopg2.errors.UndefinedFile: could not open file "/tmp/prcatice_file.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2022-11-30T09:09:40.683+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=pratice_pg, task_id=pg_prepare, execution_date=20221130T090937, start_date=20221130T090940, end_date=20221130T090940
[2022-11-30T09:09:40.690+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 700 for task pg_prepare (could not open file "/tmp/prcatice_file.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 2743)
[2022-11-30T09:09:40.727+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-30T09:09:40.742+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
