[2022-11-30T10:42:14.027+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: pratice_pg.send_email manual__2022-11-30T10:42:06.368193+00:00 [queued]>
[2022-11-30T10:42:14.032+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: pratice_pg.send_email manual__2022-11-30T10:42:06.368193+00:00 [queued]>
[2022-11-30T10:42:14.032+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T10:42:14.032+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-30T10:42:14.033+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T10:42:14.039+0000] {taskinstance.py:1383} INFO - Executing <Task(EmailOperator): send_email> on 2022-11-30 10:42:06.368193+00:00
[2022-11-30T10:42:14.042+0000] {standard_task_runner.py:55} INFO - Started process 202 to run task
[2022-11-30T10:42:14.045+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pratice_pg', 'send_email', 'manual__2022-11-30T10:42:06.368193+00:00', '--job-id', '730', '--raw', '--subdir', 'DAGS_FOLDER/practice_pg.py', '--cfg-path', '/tmp/tmpqi8qkuzh']
[2022-11-30T10:42:14.046+0000] {standard_task_runner.py:83} INFO - Job 730: Subtask send_email
[2022-11-30T10:42:14.082+0000] {task_command.py:376} INFO - Running <TaskInstance: pratice_pg.send_email manual__2022-11-30T10:42:06.368193+00:00 [running]> on host 481f60569de1
[2022-11-30T10:42:14.127+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pratice_pg
AIRFLOW_CTX_TASK_ID=send_email
AIRFLOW_CTX_EXECUTION_DATE=2022-11-30T10:42:06.368193+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-30T10:42:06.368193+00:00
[2022-11-30T10:42:14.133+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:120: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2022-11-30T10:42:14.133+0000] {configuration.py:569} WARNING - section/key [smtp/smtp_user] not found in config
[2022-11-30T10:42:14.133+0000] {email.py:229} INFO - Email alerting: attempt 1
[2022-11-30T10:42:14.133+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 87, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 72, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 231, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 265, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2022-11-30T10:42:14.138+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=pratice_pg, task_id=send_email, execution_date=20221130T104206, start_date=20221130T104214, end_date=20221130T104214
[2022-11-30T10:42:14.143+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 730 for task send_email ([Errno 99] Cannot assign requested address; 202)
[2022-11-30T10:42:14.178+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-30T10:42:14.188+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
